name: test
channels:

  - conda-forge

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - mbuild>=0.16.0
  - packmol=1!18.013
    # Testing
  - pytest
  - pytest-cov
  - codecov

    # Pip-only installs
  #- pip:
  #  - codecov

